**Load Data**

In [1]:
import pandas as pd

df=pd.read_csv("..\data\Sample - Superstore.csv",encoding='latin1')
df.columns=df.columns.str.strip()
df['Order Date']=pd.to_datetime(df['Order Date'])


monthly_sales=(df.set_index('Order Date').resample('M')['Sales'].sum().to_frame())
monthly_sales.head()

C:\Users\ASUS\AppData\Local\Temp\ipykernel_32704\1750131056.py:8: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  monthly_sales=(df.set_index('Order Date').resample('M')['Sales'].sum().to_frame())

                Sales
Order Date
2014-01-31  14236.895
2014-02-28   4519.892
2014-03-31  55691.009
2014-04-30  28295.345
2014-05-31  23648.287

**Creating Time Based Data**

In [2]:
monthly_sales.index=pd.to_datetime(monthly_sales.index)
monthly_sales['month']=monthly_sales.index.month
monthly_sales['year']=monthly_sales.index.year

monthly_sales.head()

                Sales  month  year
Order Date
2014-01-31  14236.895      1  2014
2014-02-28   4519.892      2  2014
2014-03-31  55691.009      3  2014
2014-04-30  28295.345      4  2014
2014-05-31  23648.287      5  2014

**Creating Lag Features**

In [3]:
monthly_sales['lag_1']=monthly_sales['Sales'].shift(1)
monthly_sales['lag_2']=monthly_sales['Sales'].shift(3)
monthly_sales['lag_3']=monthly_sales['Sales'].shift(6)

**Rolling Statistics**

In [4]:
monthly_sales['rolling_mean_3']=monthly_sales['Sales'].shift(1).rolling(window=3).mean()
monthly_sales['rolling_mean_6']=monthly_sales['Sales'].shift(1).rolling(window=6).mean()
monthly_sales.head()

,Sales,month,year,lag_1,lag_2,lag_3,rolling_mean_3,rolling_mean_6
Order Date,,,,,,,,
2014-01-31,14236.895,1,2014,NaN,NaN,NaN,NaN,NaN
2014-02-28,4519.892,2,2014,14236.895,NaN,NaN,NaN,NaN
2014-03-31,55691.009,3,2014,4519.892,NaN,NaN,NaN,NaN
2014-04-30,28295.345,4,2014,55691.009,14236.895,NaN,24815.932,NaN
2014-05-31,23648.287,5,2014,28295.345,4519.892,NaN,29502.082,NaN

**Drop Missing Values**

In [5]:
monthly_sales=monthly_sales.dropna()

monthly_sales.head()

,Sales,month,year,lag_1,lag_2,lag_3,rolling_mean_3,rolling_mean_6
Order Date,,,,,,,,
2014-07-31,33946.3930,7,2014,34595.1276,28295.3450,14236.895,28846.253200,26831.092600
2014-08-31,27909.4685,8,2014,33946.3930,23648.2870,4519.892,30729.935867,30116.008933
2014-09-30,81777.3508,9,2014,27909.4685,34595.1276,55691.009,32150.329700,34014.271683
2014-10-31,31453.3930,10,2014,81777.3508,33946.3930,28295.345,47877.737433,38361.995317
2014-11-30,78628.7167,11,2014,31453.3930,27909.4685,23648.287,47046.737433,38888.336650

In [10]:
monthly_sales.reset_index()
monthly_sales.head()

,Sales,month,year,lag_1,lag_2,lag_3,rolling_mean_3,rolling_mean_6
Order Date,,,,,,,,
2014-07-31,33946.3930,7,2014,34595.1276,28295.3450,14236.895,28846.253200,26831.092600
2014-08-31,27909.4685,8,2014,33946.3930,23648.2870,4519.892,30729.935867,30116.008933
2014-09-30,81777.3508,9,2014,27909.4685,34595.1276,55691.009,32150.329700,34014.271683
2014-10-31,31453.3930,10,2014,81777.3508,33946.3930,28295.345,47877.737433,38361.995317
2014-11-30,78628.7167,11,2014,31453.3930,27909.4685,23648.287,47046.737433,38888.336650

**Saving the feature Engineered Data**

In [11]:
monthly_sales.to_csv("..\data\monthly_sales_features.csv")